keyfigures_columns_2017 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "WmoClienten_86": "n_wmo_clients",
    "GemiddeldInkomenPerInkomensontvanger_65": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_72": "avg_std_income",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "unmarried",
    "Gehuwd_14": "married",
    "Gescheiden_15": "devorced",
    "Verweduwd_16": "widowed",
    "WestersTotaal_17": "western",
    "NietWestersTotaal_18": "non_western",
    "Bevolkingsdichtheid_33": "population_density",
    "Nettoarbeidsparticipatie_64": "labor_participation",
    "AfstandTotHuisartsenpraktijk_94": "dist_doctor",
    "AfstandTotGroteSupermarkt_95": "dist_store",
    "AfstandTotKinderdagverblijf_96": "dist_daycare",
}

keyfigures_columns_2018 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "WmoClienten_86": "n_wmo_clients",
    "GemiddeldInkomenPerInkomensontvanger_68": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_72": "avg_std_income",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "unmarried",
    "Gehuwd_14": "married",
    "Gescheiden_15": "devorced",
    "Verweduwd_16": "widowed",
    "WestersTotaal_17": "western",
    "NietWestersTotaal_18": "non_western",
    "Bevolkingsdichtheid_33": "population_density",
    "Nettoarbeidsparticipatie_64": "labor_participation",
    "AfstandTotHuisartsenpraktijk_105": "dist_doctor",
    "AfstandTotGroteSupermarkt_106": "dist_store",
    "AfstandTotKinderdagverblijf_107": "dist_daycare",
}

keyfigures_columns_2019 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "WmoClienten_89": "n_wmo_clients",
    "GemiddeldInkomenPerInkomensontvanger_71": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_75": "avg_std_income",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "unmarried",
    "Gehuwd_14": "married",
    "Gescheiden_15": "devorced",
    "Verweduwd_16": "widowed",
    "WestersTotaal_17": "western",
    "NietWestersTotaal_18": "non_western",
    "Bevolkingsdichtheid_33": "population_density",
    "Nettoarbeidsparticipatie_67": "labor_participation",
    "AfstandTotHuisartsenpraktijk_105": "dist_doctor",
    "AfstandTotGroteSupermarkt_106": "dist_store",
    "AfstandTotKinderdagverblijf_107": "dist_daycare",
}

keyfigures_columns_2020 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "WmoClienten_89": "n_wmo_clients",
    "GemiddeldInkomenPerInkomensontvanger_71": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_75": "avg_std_income",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "unmarried",
    "Gehuwd_14": "married",
    "Gescheiden_15": "devorced",
    "Verweduwd_16": "widowed",
    "WestersTotaal_17": "western",
    "NietWestersTotaal_18": "non_western",
    "Bevolkingsdichtheid_33": "population_density",
    "Nettoarbeidsparticipatie_67": "labor_participation",
    "AfstandTotHuisartsenpraktijk_105": "dist_doctor",
    "AfstandTotGroteSupermarkt_106": "dist_store",
    "AfstandTotKinderdagverblijf_107": "dist_daycare",
}
