keyfigures_columns_2017 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "n_unmarried",
    "Gehuwd_14": "n_married",
    "Gescheiden_15": "n_devorced",
    "Verweduwd_16": "n_widowed",
    "WestersTotaal_17": "n_western",
    "NietWestersTotaal_18": "n_non_western",
    "OppervlakteLand_100": "land_area_ha",
    "Nettoarbeidsparticipatie_64": "labor_participation",
    "GemiddeldInkomenPerInkomensontvanger_65": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_72": "avg_std_income",
    "PersonenPerSoortUitkeringBijstand_74": "n_benefit_welfare",
    "PersonenPerSoortUitkeringAO_75": "n_benefit_unfitforwork",
    "PersonenPerSoortUitkeringWW_76": "n_benefit_unemployed",
    "AfstandTotHuisartsenpraktijk_94": "dist_doctor",
    "AfstandTotGroteSupermarkt_95": "dist_store",
    "AfstandTotKinderdagverblijf_96": "dist_daycare",
}

keyfigures_columns_2018 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "n_unmarried",
    "Gehuwd_14": "n_married",
    "Gescheiden_15": "n_devorced",
    "Verweduwd_16": "n_widowed",
    "WestersTotaal_17": "n_western",
    "NietWestersTotaal_18": "n_non_western",
    "OppervlakteLand_111": "land_area_ha",
    "Nettoarbeidsparticipatie_64": "labor_participation",
    "GemiddeldInkomenPerInkomensontvanger_68": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_72": "avg_std_income",
    "PersonenPerSoortUitkeringBijstand_80": "n_benefit_welfare",
    "PersonenPerSoortUitkeringAO_81": "n_benefit_unfitforwork",
    "PersonenPerSoortUitkeringWW_82": "n_benefit_unemployed",
    "AfstandTotHuisartsenpraktijk_105": "dist_doctor",
    "AfstandTotGroteSupermarkt_106": "dist_store",
    "AfstandTotKinderdagverblijf_107": "dist_daycare",
}

keyfigures_columns_2019 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "n_unmarried",
    "Gehuwd_14": "n_married",
    "Gescheiden_15": "n_devorced",
    "Verweduwd_16": "n_widowed",
    "WestersTotaal_17": "n_western",
    "NietWestersTotaal_18": "n_non_western",
    "OppervlakteLand_111": "land_area_ha",
    "Nettoarbeidsparticipatie_67": "labor_participation",
    "GemiddeldInkomenPerInkomensontvanger_71": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_75": "avg_std_income",
    "PersonenPerSoortUitkeringBijstand_83": "n_benefit_welfare",
    "PersonenPerSoortUitkeringAO_84": "n_benefit_unfitforwork",
    "PersonenPerSoortUitkeringWW_85": "n_benefit_unemployed",
    "AfstandTotHuisartsenpraktijk_105": "dist_doctor",
    "AfstandTotGroteSupermarkt_106": "dist_store",
    "AfstandTotKinderdagverblijf_107": "dist_daycare",
}

keyfigures_columns_2020 = {
    "Codering_3": "mun_code",
    "WijkenEnBuurten": "mun_name",
    "AantalInwoners_5": "n_inhabitants",
    "Mannen_6": "n_male",
    "Vrouwen_7": "n_female",
    "k_0Tot15Jaar_8": "age_0_15",
    "k_15Tot25Jaar_9": "age_15_25",
    "k_25Tot45Jaar_10": "age_25_45",
    "k_45Tot65Jaar_11": "age_45_65",
    "k_65JaarOfOuder_12": "age_65_plus",
    "Ongehuwd_13": "n_unmarried",
    "Gehuwd_14": "n_married",
    "Gescheiden_15": "n_devorced",
    "Verweduwd_16": "n_widowed",
    "WestersTotaal_17": "n_western",
    "NietWestersTotaal_18": "n_non_western",
    "OppervlakteLand_111": "land_area_ha",
    "Nettoarbeidsparticipatie_67": "labor_participation",
    "GemiddeldInkomenPerInkomensontvanger_71": "avg_income",
    "GemGestandaardiseerdInkomenVanHuish_75": "avg_std_income",
    "PersonenPerSoortUitkeringBijstand_83": "n_benefit_welfare",
    "PersonenPerSoortUitkeringAO_84": "n_benefit_unfitforwork",
    "PersonenPerSoortUitkeringWW_85": "n_benefit_unemployed",
    "AfstandTotHuisartsenpraktijk_105": "dist_doctor",
    "AfstandTotGroteSupermarkt_106": "dist_store",
    "AfstandTotKinderdagverblijf_107": "dist_daycare",
}
